version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t seanhess/haskell:18.25

     # deploy the image
     - run: docker push seanhess/haskell:18.25
